baseURL = "https://developer.eu.mybuildings.abb.com"
languageCode = "en-us"
defaultContentLanguage = "en-us"
disableHugoGeneratorInject = true
title = "ABB Developer Portal (Addons)"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]
enableGitInfo = true
relativeURLs = true
uglyurls = true

[markup.highlight]
  codeFences = true


[markup.goldmark.renderer]
  # required to allow raw html in markdown, such as <br>
  unsafe = true
